// <auto-generated />
using System;
using MarketMind.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MarketMind.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425165021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketMind.Domain.Entities.AIAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_text");

                    b.Property<Guid[]>("SourceArticleIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("source_article_ids");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_key");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_ai_analyses");

                    b.HasIndex("ValidUntil")
                        .HasDatabaseName("ix_ai_analyses_valid_until");

                    b.HasIndex("Type", "TargetKey")
                        .HasDatabaseName("ix_ai_analyses_type_key");

                    b.ToTable("ai_analyses", (string)null);
                });

            modelBuilder.Entity("MarketMind.Domain.Entities.FoSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<decimal>("MaxPain")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_pain");

                    b.Property<decimal>("PutCallRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("put_call_ratio");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_fo_snapshots");

                    b.HasIndex("Symbol", "CapturedAt")
                        .HasDatabaseName("ix_fo_snapshots_symbol_captured");

                    b.ToTable("fo_snapshots", (string)null);
                });

            modelBuilder.Entity("MarketMind.Domain.Entities.MarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<decimal>("ChangeAbsolute")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("change_absolute");

                    b.Property<decimal>("ChangePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("change_percent");

                    b.Property<decimal?>("DayHigh")
                        .HasColumnType("numeric")
                        .HasColumnName("day_high");

                    b.Property<decimal?>("DayLow")
                        .HasColumnType("numeric")
                        .HasColumnName("day_low");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("module");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("symbol");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_market_snapshots");

                    b.HasIndex("Symbol", "CapturedAt")
                        .HasDatabaseName("ix_market_snapshots_symbol_captured");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("MarketMind.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string[]>("AffectedSectors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("affected_sectors");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("headline");

                    b.Property<bool>("IsEmbedded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_embedded");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sentiment");

                    b.Property<float>("SentimentScore")
                        .HasColumnType("real")
                        .HasColumnName("sentiment_score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_articles");

                    b.HasIndex("IsEmbedded")
                        .HasDatabaseName("ix_news_articles_is_embedded");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_news_articles_published_at");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_news_articles_url");

                    b.ToTable("news_articles", (string)null);
                });

            modelBuilder.Entity("MarketMind.Domain.Entities.SectorSentiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ArticleCount")
                        .HasColumnType("integer")
                        .HasColumnName("article_count");

                    b.Property<float>("BullishScore")
                        .HasColumnType("real")
                        .HasColumnName("bullish_score");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Overall")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sector");

                    b.HasKey("Id")
                        .HasName("pk_sector_sentiments");

                    b.HasIndex("Sector", "Date")
                        .HasDatabaseName("ix_sector_sentiments_sector_date");

                    b.ToTable("sector_sentiments", (string)null);
                });

            modelBuilder.Entity("MarketMind.Domain.Entities.FoSnapshot", b =>
                {
                    b.OwnsMany("MarketMind.Domain.Entities.OiStrike", "TopStrikes", b1 =>
                        {
                            b1.Property<Guid>("FoSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<long>("CallOI")
                                .HasColumnType("bigint");

                            b1.Property<long>("PutOI")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Strike")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("FoSnapshotId", "Id");

                            b1.ToTable("fo_snapshots");

                            b1.ToJson("top_strikes");

                            b1.WithOwner()
                                .HasForeignKey("FoSnapshotId")
                                .HasConstraintName("fk_fo_snapshots_fo_snapshots_fo_snapshot_id");
                        });

                    b.Navigation("TopStrikes");
                });
#pragma warning restore 612, 618
        }
    }
}
